server:
  port: 8090

spring:
  application:
    name: Library-management-system-API
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
